services:
  app:
    container_name: expenses-api-app
    image: yiisoftware/yii2-php:8.3-apache
    ports:
      - "8000:80"
    volumes:
      - .:/app:delegated

  db:
    container_name: expenses-api-db
    image: mysql:latest
    volumes:
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysqldata:/var/lib/mysql
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_TCP_PORT: ${DB_PORT}

volumes:
  mysqldata: